#!/bin/bash

echo "🚀 PCMI Test Automation Script v1.1 - Stable Version"
echo "===================================================="
echo "Date: $(date)"
echo

echo "🧹 1. Full container cleanup..."
docker compose down -v --remove-orphans

echo "🏗️  2. Fresh build and start..."
docker compose up -d --build

echo "⏳ 3. Waiting for services to start (15 seconds)..."
sleep 15

echo "🔍 4. Health Check..."
curl -s -f http://localhost:8000/v1/health > /dev/null && echo "✅ API healthy" || { echo "❌ API not reachable"; exit 1; }

echo "📤 5. Store a new test memory..."
cat > /tmp/pcmi_test_payload.json << JSON
{
  "path": "root.test.autotest.$(date +%s)",
  "content": "Automated test generated by script - verify embedding + retrieve",
  "metadata": {"author": "marco", "test": "auto"},
  "embedding_model": "text-embedding-3-large",
  "tags": ["auto-test"]
}
JSON

curl -s -X POST http://localhost:8000/v1/memories \
  -H "Content-Type: application/json" \
  -H "X-API-Key: testkey123" \
  -d @/tmp/pcmi_test_payload.json | jq -r '.'

echo

echo "⏳ 6. Waiting 30 seconds for the worker to generate the embedding..."
sleep 30

echo "📥 7. Retrieve with path_prefix root.test..."
curl -s -X POST http://localhost:8000/v1/retrieve \
  -H "Content-Type: application/json" \
  -H "X-API-Key: testkey123" \
  -d '{
    "path_prefix": "root.test",
    "limit": 10
  }' | jq '.'

echo

echo "📋 8. Last Embedding Worker logs:"
docker compose logs worker --tail=20

echo
echo "✅ Tests completed."
echo "To see live worker logs: docker compose logs -f worker"
