// PCMI Admin gRPC API (PR #5 — Admin + /metrics gRPC parity).
//
// Mirrors the operations that today are HTTP-only:
//
//   POST   /v1/admin/tenants             → AdminService.CreateTenant
//   GET    /v1/admin/tenants             → AdminService.ListTenants
//   POST   /v1/admin/api-keys            → AdminService.CreateAPIKey
//   POST   /v1/admin/api-keys/{id}/rotate → AdminService.RotateAPIKey
//   GET    /v1/admin/api-keys?tenant=…   → AdminService.ListAPIKeys
//
// All RPCs require role=admin (enforced by the same RBAC middleware that
// guards the HTTP routes — see internal/middleware/admin.go). The proto
// pairs use server-streamed pagination via opaque cursor tokens
// (model.Cursor), matching the new keyset pagination contract.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pcmi/v1/admin.proto

package pcmiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTenantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Slug  string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Settings is a JSON blob (object) of tenant-scoped configuration.
	// Empty string defaults to "{}". Schema is up to the caller — PCMI
	// treats it as opaque pass-through.
	SettingsJson  string `protobuf:"bytes,3,opt,name=settings_json,json=settingsJson,proto3" json:"settings_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_pcmi_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTenantRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTenantRequest) GetSettingsJson() string {
	if x != nil {
		return x.SettingsJson
	}
	return ""
}

type TenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantResponse) Reset() {
	*x = TenantResponse{}
	mi := &file_pcmi_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantResponse) ProtoMessage() {}

func (x *TenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantResponse.ProtoReflect.Descriptor instead.
func (*TenantResponse) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *TenantResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TenantResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *TenantResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TenantResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListTenantsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cursor (opaque, base64url JSON) — see model.Cursor.
	// Empty means "first page".
	Cursor string `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Limit clamped server-side (default 50, max 200).
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsRequest) Reset() {
	*x = ListTenantsRequest{}
	mi := &file_pcmi_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsRequest) ProtoMessage() {}

func (x *ListTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantsRequest) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListTenantsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListTenantsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListTenantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*TenantResponse      `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsResponse) Reset() {
	*x = ListTenantsResponse{}
	mi := &file_pcmi_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsResponse) ProtoMessage() {}

func (x *ListTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsResponse.ProtoReflect.Descriptor instead.
func (*ListTenantsResponse) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ListTenantsResponse) GetTenants() []*TenantResponse {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *ListTenantsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListTenantsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type CreateAPIKeyRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Human-readable label ("ci-bot", "alice's laptop").
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Role: "admin" | "write" | "user" | "readonly". Validated server-side.
	Role string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	// Optional RFC3339 expiry. Empty = never expires.
	ExpiresAt     string `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyRequest) Reset() {
	*x = CreateAPIKeyRequest{}
	mi := &file_pcmi_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyRequest) ProtoMessage() {}

func (x *CreateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAPIKeyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type RotateAPIKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Optional new label; empty preserves the existing one.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateAPIKeyRequest) Reset() {
	*x = RotateAPIKeyRequest{}
	mi := &file_pcmi_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateAPIKeyRequest) ProtoMessage() {}

func (x *RotateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*RotateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *RotateAPIKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RotateAPIKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type APIKeyResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name     string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Role     string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	// The cleartext API key — returned ONCE on create/rotate; never readable
	// again (the server stores only sha256(key)).
	ApiKey        string                 `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyResponse) Reset() {
	*x = APIKeyResponse{}
	mi := &file_pcmi_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyResponse) ProtoMessage() {}

func (x *APIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyResponse.ProtoReflect.Descriptor instead.
func (*APIKeyResponse) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *APIKeyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *APIKeyResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *APIKeyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIKeyResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *APIKeyResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *APIKeyResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *APIKeyResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type ListAPIKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAPIKeysRequest) Reset() {
	*x = ListAPIKeysRequest{}
	mi := &file_pcmi_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAPIKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAPIKeysRequest) ProtoMessage() {}

func (x *ListAPIKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAPIKeysRequest.ProtoReflect.Descriptor instead.
func (*ListAPIKeysRequest) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ListAPIKeysRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListAPIKeysRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListAPIKeysRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type APIKeySummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeySummary) Reset() {
	*x = APIKeySummary{}
	mi := &file_pcmi_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeySummary) ProtoMessage() {}

func (x *APIKeySummary) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeySummary.ProtoReflect.Descriptor instead.
func (*APIKeySummary) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *APIKeySummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *APIKeySummary) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *APIKeySummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIKeySummary) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *APIKeySummary) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *APIKeySummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *APIKeySummary) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type ListAPIKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*APIKeySummary       `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAPIKeysResponse) Reset() {
	*x = ListAPIKeysResponse{}
	mi := &file_pcmi_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAPIKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAPIKeysResponse) ProtoMessage() {}

func (x *ListAPIKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAPIKeysResponse.ProtoReflect.Descriptor instead.
func (*ListAPIKeysResponse) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ListAPIKeysResponse) GetKeys() []*APIKeySummary {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ListAPIKeysResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListAPIKeysResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_pcmi_v1_admin_proto protoreflect.FileDescriptor

const file_pcmi_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x13pcmi/v1/admin.proto\x12\apcmi.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"b\n" +
	"\x13CreateTenantRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rsettings_json\x18\x03 \x01(\tR\fsettingsJson\"\x83\x01\n" +
	"\x0eTenantResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"B\n" +
	"\x12ListTenantsRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x84\x01\n" +
	"\x13ListTenantsResponse\x121\n" +
	"\atenants\x18\x01 \x03(\v2\x17.pcmi.v1.TenantResponseR\atenants\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"y\n" +
	"\x13CreateAPIKeyRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\tR\texpiresAt\"9\n" +
	"\x13RotateAPIKeyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xd8\x01\n" +
	"\x0eAPIKeyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x17\n" +
	"\aapi_key\x18\x05 \x01(\tR\x06apiKey\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\tR\texpiresAt\"_\n" +
	"\x12ListAPIKeysRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xdb\x01\n" +
	"\rAPIKeySummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\tR\texpiresAt\"}\n" +
	"\x13ListAPIKeysResponse\x12*\n" +
	"\x04keys\x18\x01 \x03(\v2\x16.pcmi.v1.APIKeySummaryR\x04keys\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore2\xf7\x02\n" +
	"\fAdminService\x12E\n" +
	"\fCreateTenant\x12\x1c.pcmi.v1.CreateTenantRequest\x1a\x17.pcmi.v1.TenantResponse\x12H\n" +
	"\vListTenants\x12\x1b.pcmi.v1.ListTenantsRequest\x1a\x1c.pcmi.v1.ListTenantsResponse\x12E\n" +
	"\fCreateAPIKey\x12\x1c.pcmi.v1.CreateAPIKeyRequest\x1a\x17.pcmi.v1.APIKeyResponse\x12E\n" +
	"\fRotateAPIKey\x12\x1c.pcmi.v1.RotateAPIKeyRequest\x1a\x17.pcmi.v1.APIKeyResponse\x12H\n" +
	"\vListAPIKeys\x12\x1b.pcmi.v1.ListAPIKeysRequest\x1a\x1c.pcmi.v1.ListAPIKeysResponseB9Z7github.com/marco-spagn/pcmi/internal/grpc/pcmiv1;pcmiv1b\x06proto3"

var (
	file_pcmi_v1_admin_proto_rawDescOnce sync.Once
	file_pcmi_v1_admin_proto_rawDescData []byte
)

func file_pcmi_v1_admin_proto_rawDescGZIP() []byte {
	file_pcmi_v1_admin_proto_rawDescOnce.Do(func() {
		file_pcmi_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pcmi_v1_admin_proto_rawDesc), len(file_pcmi_v1_admin_proto_rawDesc)))
	})
	return file_pcmi_v1_admin_proto_rawDescData
}

var file_pcmi_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pcmi_v1_admin_proto_goTypes = []any{
	(*CreateTenantRequest)(nil),   // 0: pcmi.v1.CreateTenantRequest
	(*TenantResponse)(nil),        // 1: pcmi.v1.TenantResponse
	(*ListTenantsRequest)(nil),    // 2: pcmi.v1.ListTenantsRequest
	(*ListTenantsResponse)(nil),   // 3: pcmi.v1.ListTenantsResponse
	(*CreateAPIKeyRequest)(nil),   // 4: pcmi.v1.CreateAPIKeyRequest
	(*RotateAPIKeyRequest)(nil),   // 5: pcmi.v1.RotateAPIKeyRequest
	(*APIKeyResponse)(nil),        // 6: pcmi.v1.APIKeyResponse
	(*ListAPIKeysRequest)(nil),    // 7: pcmi.v1.ListAPIKeysRequest
	(*APIKeySummary)(nil),         // 8: pcmi.v1.APIKeySummary
	(*ListAPIKeysResponse)(nil),   // 9: pcmi.v1.ListAPIKeysResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_pcmi_v1_admin_proto_depIdxs = []int32{
	10, // 0: pcmi.v1.TenantResponse.created_at:type_name -> google.protobuf.Timestamp
	1,  // 1: pcmi.v1.ListTenantsResponse.tenants:type_name -> pcmi.v1.TenantResponse
	10, // 2: pcmi.v1.APIKeyResponse.created_at:type_name -> google.protobuf.Timestamp
	10, // 3: pcmi.v1.APIKeySummary.created_at:type_name -> google.protobuf.Timestamp
	8,  // 4: pcmi.v1.ListAPIKeysResponse.keys:type_name -> pcmi.v1.APIKeySummary
	0,  // 5: pcmi.v1.AdminService.CreateTenant:input_type -> pcmi.v1.CreateTenantRequest
	2,  // 6: pcmi.v1.AdminService.ListTenants:input_type -> pcmi.v1.ListTenantsRequest
	4,  // 7: pcmi.v1.AdminService.CreateAPIKey:input_type -> pcmi.v1.CreateAPIKeyRequest
	5,  // 8: pcmi.v1.AdminService.RotateAPIKey:input_type -> pcmi.v1.RotateAPIKeyRequest
	7,  // 9: pcmi.v1.AdminService.ListAPIKeys:input_type -> pcmi.v1.ListAPIKeysRequest
	1,  // 10: pcmi.v1.AdminService.CreateTenant:output_type -> pcmi.v1.TenantResponse
	3,  // 11: pcmi.v1.AdminService.ListTenants:output_type -> pcmi.v1.ListTenantsResponse
	6,  // 12: pcmi.v1.AdminService.CreateAPIKey:output_type -> pcmi.v1.APIKeyResponse
	6,  // 13: pcmi.v1.AdminService.RotateAPIKey:output_type -> pcmi.v1.APIKeyResponse
	9,  // 14: pcmi.v1.AdminService.ListAPIKeys:output_type -> pcmi.v1.ListAPIKeysResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pcmi_v1_admin_proto_init() }
func file_pcmi_v1_admin_proto_init() {
	if File_pcmi_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pcmi_v1_admin_proto_rawDesc), len(file_pcmi_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pcmi_v1_admin_proto_goTypes,
		DependencyIndexes: file_pcmi_v1_admin_proto_depIdxs,
		MessageInfos:      file_pcmi_v1_admin_proto_msgTypes,
	}.Build()
	File_pcmi_v1_admin_proto = out.File
	file_pcmi_v1_admin_proto_goTypes = nil
	file_pcmi_v1_admin_proto_depIdxs = nil
}
