// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pcmi/v1/memory.proto

package pcmiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{0}
}

type ReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ready" or "not_ready"
	DatabaseOk    bool                   `protobuf:"varint,2,opt,name=database_ok,json=databaseOk,proto3" json:"database_ok,omitempty"`
	RedisOk       bool                   `protobuf:"varint,3,opt,name=redis_ok,json=redisOk,proto3" json:"redis_ok,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{1}
}

func (x *ReadyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReadyResponse) GetDatabaseOk() bool {
	if x != nil {
		return x.DatabaseOk
	}
	return false
}

func (x *ReadyResponse) GetRedisOk() bool {
	if x != nil {
		return x.RedisOk
	}
	return false
}

func (x *ReadyResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type StoreRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Path         string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content      string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	MetadataJson string                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	ApiKey       string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// Same semantics as REST POST /v1/memories JSON body.
	Tags           []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	EmbeddingModel string   `protobuf:"bytes,6,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`
	EmbeddingSpace string   `protobuf:"bytes,7,opt,name=embedding_space,json=embeddingSpace,proto3" json:"embedding_space,omitempty"`
	SourceAgentId  string   `protobuf:"bytes,8,opt,name=source_agent_id,json=sourceAgentId,proto3" json:"source_agent_id,omitempty"`
	EncryptContent bool     `protobuf:"varint,9,opt,name=encrypt_content,json=encryptContent,proto3" json:"encrypt_content,omitempty"`
	// Optional TTL, RFC3339 or RFC3339Nano.
	ExpiresAtRfc3339 string `protobuf:"bytes,10,opt,name=expires_at_rfc3339,json=expiresAtRfc3339,proto3" json:"expires_at_rfc3339,omitempty"`
	// Optional client-supplied embedding vector (same as REST JSON "embedding"); dimension must match DB (1536).
	Embedding     []float32 `protobuf:"fixed32,11,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{2}
}

func (x *StoreRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StoreRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StoreRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *StoreRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *StoreRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *StoreRequest) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

func (x *StoreRequest) GetEmbeddingSpace() string {
	if x != nil {
		return x.EmbeddingSpace
	}
	return ""
}

func (x *StoreRequest) GetSourceAgentId() string {
	if x != nil {
		return x.SourceAgentId
	}
	return ""
}

func (x *StoreRequest) GetEncryptContent() bool {
	if x != nil {
		return x.EncryptContent
	}
	return false
}

func (x *StoreRequest) GetExpiresAtRfc3339() string {
	if x != nil {
		return x.ExpiresAtRfc3339
	}
	return ""
}

func (x *StoreRequest) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	SupersededId  *int64                 `protobuf:"varint,4,opt,name=superseded_id,json=supersededId,proto3,oneof" json:"superseded_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{3}
}

func (x *StoreResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StoreResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StoreResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StoreResponse) GetSupersededId() int64 {
	if x != nil && x.SupersededId != nil {
		return *x.SupersededId
	}
	return 0
}

type BatchStoreItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Path             string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content          string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	MetadataJson     string                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	Tags             []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	EmbeddingModel   string                 `protobuf:"bytes,5,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`
	EmbeddingSpace   string                 `protobuf:"bytes,6,opt,name=embedding_space,json=embeddingSpace,proto3" json:"embedding_space,omitempty"`
	SourceAgentId    string                 `protobuf:"bytes,7,opt,name=source_agent_id,json=sourceAgentId,proto3" json:"source_agent_id,omitempty"`
	EncryptContent   bool                   `protobuf:"varint,8,opt,name=encrypt_content,json=encryptContent,proto3" json:"encrypt_content,omitempty"`
	ExpiresAtRfc3339 string                 `protobuf:"bytes,9,opt,name=expires_at_rfc3339,json=expiresAtRfc3339,proto3" json:"expires_at_rfc3339,omitempty"`
	Embedding        []float32              `protobuf:"fixed32,10,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchStoreItem) Reset() {
	*x = BatchStoreItem{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStoreItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStoreItem) ProtoMessage() {}

func (x *BatchStoreItem) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStoreItem.ProtoReflect.Descriptor instead.
func (*BatchStoreItem) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{4}
}

func (x *BatchStoreItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BatchStoreItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BatchStoreItem) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *BatchStoreItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *BatchStoreItem) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

func (x *BatchStoreItem) GetEmbeddingSpace() string {
	if x != nil {
		return x.EmbeddingSpace
	}
	return ""
}

func (x *BatchStoreItem) GetSourceAgentId() string {
	if x != nil {
		return x.SourceAgentId
	}
	return ""
}

func (x *BatchStoreItem) GetEncryptContent() bool {
	if x != nil {
		return x.EncryptContent
	}
	return false
}

func (x *BatchStoreItem) GetExpiresAtRfc3339() string {
	if x != nil {
		return x.ExpiresAtRfc3339
	}
	return ""
}

func (x *BatchStoreItem) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type BatchStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BatchStoreItem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStoreRequest) Reset() {
	*x = BatchStoreRequest{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStoreRequest) ProtoMessage() {}

func (x *BatchStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStoreRequest.ProtoReflect.Descriptor instead.
func (*BatchStoreRequest) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{5}
}

func (x *BatchStoreRequest) GetItems() []*BatchStoreItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BatchStoreRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type BatchStoreItemResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	SupersededId  *int64                 `protobuf:"varint,5,opt,name=superseded_id,json=supersededId,proto3,oneof" json:"superseded_id,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStoreItemResult) Reset() {
	*x = BatchStoreItemResult{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStoreItemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStoreItemResult) ProtoMessage() {}

func (x *BatchStoreItemResult) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStoreItemResult.ProtoReflect.Descriptor instead.
func (*BatchStoreItemResult) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{6}
}

func (x *BatchStoreItemResult) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BatchStoreItemResult) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BatchStoreItemResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BatchStoreItemResult) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BatchStoreItemResult) GetSupersededId() int64 {
	if x != nil && x.SupersededId != nil {
		return *x.SupersededId
	}
	return 0
}

func (x *BatchStoreItemResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchStoreResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Results       []*BatchStoreItemResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStoreResponse) Reset() {
	*x = BatchStoreResponse{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStoreResponse) ProtoMessage() {}

func (x *BatchStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStoreResponse.ProtoReflect.Descriptor instead.
func (*BatchStoreResponse) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{7}
}

func (x *BatchStoreResponse) GetResults() []*BatchStoreItemResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BatchStoreResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RetrieveRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PathPrefix string                 `protobuf:"bytes,1,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	Query      string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Limit      int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	ApiKey     string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// Same semantics as REST POST /v1/retrieve JSON body.
	Tags []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	// "any" (default when empty) or "all".
	TagsMatch string `protobuf:"bytes,6,opt,name=tags_match,json=tagsMatch,proto3" json:"tags_match,omitempty"`
	// Optional point-in-time filter, RFC3339 or RFC3339Nano (e.g. 2006-01-02T15:04:05Z07:00).
	AsOfRfc3339    string `protobuf:"bytes,7,opt,name=as_of_rfc3339,json=asOfRfc3339,proto3" json:"as_of_rfc3339,omitempty"`
	SourceAgentId  string `protobuf:"bytes,8,opt,name=source_agent_id,json=sourceAgentId,proto3" json:"source_agent_id,omitempty"`
	EmbeddingSpace string `protobuf:"bytes,9,opt,name=embedding_space,json=embeddingSpace,proto3" json:"embedding_space,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{8}
}

func (x *RetrieveRequest) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *RetrieveRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RetrieveRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RetrieveRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *RetrieveRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RetrieveRequest) GetTagsMatch() string {
	if x != nil {
		return x.TagsMatch
	}
	return ""
}

func (x *RetrieveRequest) GetAsOfRfc3339() string {
	if x != nil {
		return x.AsOfRfc3339
	}
	return ""
}

func (x *RetrieveRequest) GetSourceAgentId() string {
	if x != nil {
		return x.SourceAgentId
	}
	return ""
}

func (x *RetrieveRequest) GetEmbeddingSpace() string {
	if x != nil {
		return x.EmbeddingSpace
	}
	return ""
}

// RetrieveEntry mirrors REST MemoryEntry in retrieve responses (v1.26.0+).
type RetrieveEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Path             string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Content          string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Version          int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	RelevanceScore   float64                `protobuf:"fixed64,5,opt,name=relevance_score,json=relevanceScore,proto3" json:"relevance_score,omitempty"`
	TenantId         string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	MetadataJson     string                 `protobuf:"bytes,7,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	Tags             []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	EmbeddingModel   string                 `protobuf:"bytes,9,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`
	EmbeddingSpace   string                 `protobuf:"bytes,10,opt,name=embedding_space,json=embeddingSpace,proto3" json:"embedding_space,omitempty"`
	ValidFromRfc3339 string                 `protobuf:"bytes,11,opt,name=valid_from_rfc3339,json=validFromRfc3339,proto3" json:"valid_from_rfc3339,omitempty"`
	ValidToRfc3339   string                 `protobuf:"bytes,12,opt,name=valid_to_rfc3339,json=validToRfc3339,proto3" json:"valid_to_rfc3339,omitempty"` // empty when current row has no valid_to
	SourceAgentId    string                 `protobuf:"bytes,13,opt,name=source_agent_id,json=sourceAgentId,proto3" json:"source_agent_id,omitempty"`
	SourceEventId    string                 `protobuf:"bytes,14,opt,name=source_event_id,json=sourceEventId,proto3" json:"source_event_id,omitempty"`
	CreatedAtRfc3339 string                 `protobuf:"bytes,15,opt,name=created_at_rfc3339,json=createdAtRfc3339,proto3" json:"created_at_rfc3339,omitempty"`
	ContentEncrypted bool                   `protobuf:"varint,16,opt,name=content_encrypted,json=contentEncrypted,proto3" json:"content_encrypted,omitempty"`
	Embedding        []float32              `protobuf:"fixed32,17,rep,packed,name=embedding,proto3" json:"embedding,omitempty"` // omitted when not loaded / null in DB
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RetrieveEntry) Reset() {
	*x = RetrieveEntry{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveEntry) ProtoMessage() {}

func (x *RetrieveEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveEntry.ProtoReflect.Descriptor instead.
func (*RetrieveEntry) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{9}
}

func (x *RetrieveEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RetrieveEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RetrieveEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RetrieveEntry) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RetrieveEntry) GetRelevanceScore() float64 {
	if x != nil {
		return x.RelevanceScore
	}
	return 0
}

func (x *RetrieveEntry) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RetrieveEntry) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *RetrieveEntry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RetrieveEntry) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

func (x *RetrieveEntry) GetEmbeddingSpace() string {
	if x != nil {
		return x.EmbeddingSpace
	}
	return ""
}

func (x *RetrieveEntry) GetValidFromRfc3339() string {
	if x != nil {
		return x.ValidFromRfc3339
	}
	return ""
}

func (x *RetrieveEntry) GetValidToRfc3339() string {
	if x != nil {
		return x.ValidToRfc3339
	}
	return ""
}

func (x *RetrieveEntry) GetSourceAgentId() string {
	if x != nil {
		return x.SourceAgentId
	}
	return ""
}

func (x *RetrieveEntry) GetSourceEventId() string {
	if x != nil {
		return x.SourceEventId
	}
	return ""
}

func (x *RetrieveEntry) GetCreatedAtRfc3339() string {
	if x != nil {
		return x.CreatedAtRfc3339
	}
	return ""
}

func (x *RetrieveEntry) GetContentEncrypted() bool {
	if x != nil {
		return x.ContentEncrypted
	}
	return false
}

func (x *RetrieveEntry) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type RetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*RetrieveEntry       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{10}
}

func (x *RetrieveResponse) GetEntries() []*RetrieveEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *RetrieveResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BatchRetrieveQuery struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PathPrefix     string                 `protobuf:"bytes,1,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	Query          string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Tags           []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	TagsMatch      string                 `protobuf:"bytes,5,opt,name=tags_match,json=tagsMatch,proto3" json:"tags_match,omitempty"`
	AsOfRfc3339    string                 `protobuf:"bytes,6,opt,name=as_of_rfc3339,json=asOfRfc3339,proto3" json:"as_of_rfc3339,omitempty"`
	SourceAgentId  string                 `protobuf:"bytes,7,opt,name=source_agent_id,json=sourceAgentId,proto3" json:"source_agent_id,omitempty"`
	EmbeddingSpace string                 `protobuf:"bytes,8,opt,name=embedding_space,json=embeddingSpace,proto3" json:"embedding_space,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchRetrieveQuery) Reset() {
	*x = BatchRetrieveQuery{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRetrieveQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRetrieveQuery) ProtoMessage() {}

func (x *BatchRetrieveQuery) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRetrieveQuery.ProtoReflect.Descriptor instead.
func (*BatchRetrieveQuery) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{11}
}

func (x *BatchRetrieveQuery) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *BatchRetrieveQuery) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *BatchRetrieveQuery) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *BatchRetrieveQuery) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *BatchRetrieveQuery) GetTagsMatch() string {
	if x != nil {
		return x.TagsMatch
	}
	return ""
}

func (x *BatchRetrieveQuery) GetAsOfRfc3339() string {
	if x != nil {
		return x.AsOfRfc3339
	}
	return ""
}

func (x *BatchRetrieveQuery) GetSourceAgentId() string {
	if x != nil {
		return x.SourceAgentId
	}
	return ""
}

func (x *BatchRetrieveQuery) GetEmbeddingSpace() string {
	if x != nil {
		return x.EmbeddingSpace
	}
	return ""
}

type BatchRetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queries       []*BatchRetrieveQuery  `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRetrieveRequest) Reset() {
	*x = BatchRetrieveRequest{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRetrieveRequest) ProtoMessage() {}

func (x *BatchRetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRetrieveRequest.ProtoReflect.Descriptor instead.
func (*BatchRetrieveRequest) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{12}
}

func (x *BatchRetrieveRequest) GetQueries() []*BatchRetrieveQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *BatchRetrieveRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type BatchRetrieveResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*RetrieveEntry       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRetrieveResult) Reset() {
	*x = BatchRetrieveResult{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRetrieveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRetrieveResult) ProtoMessage() {}

func (x *BatchRetrieveResult) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRetrieveResult.ProtoReflect.Descriptor instead.
func (*BatchRetrieveResult) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{13}
}

func (x *BatchRetrieveResult) GetEntries() []*RetrieveEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *BatchRetrieveResult) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BatchRetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*BatchRetrieveResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRetrieveResponse) Reset() {
	*x = BatchRetrieveResponse{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRetrieveResponse) ProtoMessage() {}

func (x *BatchRetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRetrieveResponse.ProtoReflect.Descriptor instead.
func (*BatchRetrieveResponse) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{14}
}

func (x *BatchRetrieveResponse) GetResults() []*BatchRetrieveResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BatchRetrieveResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RetrieveStreamHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveStreamHeader) Reset() {
	*x = RetrieveStreamHeader{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveStreamHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveStreamHeader) ProtoMessage() {}

func (x *RetrieveStreamHeader) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveStreamHeader.ProtoReflect.Descriptor instead.
func (*RetrieveStreamHeader) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{15}
}

func (x *RetrieveStreamHeader) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RetrieveStreamMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*RetrieveStreamMsg_Header
	//	*RetrieveStreamMsg_Entry
	Msg           isRetrieveStreamMsg_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveStreamMsg) Reset() {
	*x = RetrieveStreamMsg{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveStreamMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveStreamMsg) ProtoMessage() {}

func (x *RetrieveStreamMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveStreamMsg.ProtoReflect.Descriptor instead.
func (*RetrieveStreamMsg) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{16}
}

func (x *RetrieveStreamMsg) GetMsg() isRetrieveStreamMsg_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *RetrieveStreamMsg) GetHeader() *RetrieveStreamHeader {
	if x != nil {
		if x, ok := x.Msg.(*RetrieveStreamMsg_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *RetrieveStreamMsg) GetEntry() *RetrieveEntry {
	if x != nil {
		if x, ok := x.Msg.(*RetrieveStreamMsg_Entry); ok {
			return x.Entry
		}
	}
	return nil
}

type isRetrieveStreamMsg_Msg interface {
	isRetrieveStreamMsg_Msg()
}

type RetrieveStreamMsg_Header struct {
	Header *RetrieveStreamHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type RetrieveStreamMsg_Entry struct {
	Entry *RetrieveEntry `protobuf:"bytes,2,opt,name=entry,proto3,oneof"`
}

func (*RetrieveStreamMsg_Header) isRetrieveStreamMsg_Msg() {}

func (*RetrieveStreamMsg_Entry) isRetrieveStreamMsg_Msg() {}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{17}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{18}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetMemoryRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Path   string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ApiKey string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// Optional exact version; 0 means latest/current.
	Version       int32  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	AsOfRfc3339   string `protobuf:"bytes,4,opt,name=as_of_rfc3339,json=asOfRfc3339,proto3" json:"as_of_rfc3339,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryRequest) Reset() {
	*x = GetMemoryRequest{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryRequest) ProtoMessage() {}

func (x *GetMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryRequest.ProtoReflect.Descriptor instead.
func (*GetMemoryRequest) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{19}
}

func (x *GetMemoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetMemoryRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetMemoryRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetMemoryRequest) GetAsOfRfc3339() string {
	if x != nil {
		return x.AsOfRfc3339
	}
	return ""
}

type GetMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *RetrieveEntry         `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryResponse) Reset() {
	*x = GetMemoryResponse{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryResponse) ProtoMessage() {}

func (x *GetMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryResponse.ProtoReflect.Descriptor instead.
func (*GetMemoryResponse) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{20}
}

func (x *GetMemoryResponse) GetEntry() *RetrieveEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type CompactRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Path           string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ApiKey         string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	KeepSuperseded int32                  `protobuf:"varint,3,opt,name=keep_superseded,json=keepSuperseded,proto3" json:"keep_superseded,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompactRequest) Reset() {
	*x = CompactRequest{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactRequest) ProtoMessage() {}

func (x *CompactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactRequest.ProtoReflect.Descriptor instead.
func (*CompactRequest) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{21}
}

func (x *CompactRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CompactRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CompactRequest) GetKeepSuperseded() int32 {
	if x != nil {
		return x.KeepSuperseded
	}
	return 0
}

type CompactResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Path           string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	DeletedCount   int32                  `protobuf:"varint,2,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	KeepSuperseded int32                  `protobuf:"varint,3,opt,name=keep_superseded,json=keepSuperseded,proto3" json:"keep_superseded,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompactResponse) Reset() {
	*x = CompactResponse{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactResponse) ProtoMessage() {}

func (x *CompactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactResponse.ProtoReflect.Descriptor instead.
func (*CompactResponse) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{22}
}

func (x *CompactResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CompactResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

func (x *CompactResponse) GetKeepSuperseded() int32 {
	if x != nil {
		return x.KeepSuperseded
	}
	return 0
}

var File_pcmi_v1_memory_proto protoreflect.FileDescriptor

const file_pcmi_v1_memory_proto_rawDesc = "" +
	"\n" +
	"\x14pcmi/v1/memory.proto\x12\apcmi.v1\"\x0e\n" +
	"\fReadyRequest\"}\n" +
	"\rReadyResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vdatabase_ok\x18\x02 \x01(\bR\n" +
	"databaseOk\x12\x19\n" +
	"\bredis_ok\x18\x03 \x01(\bR\aredisOk\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\xfd\x02\n" +
	"\fStoreRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\tR\fmetadataJson\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12'\n" +
	"\x0fembedding_model\x18\x06 \x01(\tR\x0eembeddingModel\x12'\n" +
	"\x0fembedding_space\x18\a \x01(\tR\x0eembeddingSpace\x12&\n" +
	"\x0fsource_agent_id\x18\b \x01(\tR\rsourceAgentId\x12'\n" +
	"\x0fencrypt_content\x18\t \x01(\bR\x0eencryptContent\x12,\n" +
	"\x12expires_at_rfc3339\x18\n" +
	" \x01(\tR\x10expiresAtRfc3339\x12\x1c\n" +
	"\tembedding\x18\v \x03(\x02R\tembedding\"\x8d\x01\n" +
	"\rStoreResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12(\n" +
	"\rsuperseded_id\x18\x04 \x01(\x03H\x00R\fsupersededId\x88\x01\x01B\x10\n" +
	"\x0e_superseded_id\"\xe6\x02\n" +
	"\x0eBatchStoreItem\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\tR\fmetadataJson\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12'\n" +
	"\x0fembedding_model\x18\x05 \x01(\tR\x0eembeddingModel\x12'\n" +
	"\x0fembedding_space\x18\x06 \x01(\tR\x0eembeddingSpace\x12&\n" +
	"\x0fsource_agent_id\x18\a \x01(\tR\rsourceAgentId\x12'\n" +
	"\x0fencrypt_content\x18\b \x01(\bR\x0eencryptContent\x12,\n" +
	"\x12expires_at_rfc3339\x18\t \x01(\tR\x10expiresAtRfc3339\x12\x1c\n" +
	"\tembedding\x18\n" +
	" \x03(\x02R\tembedding\"[\n" +
	"\x11BatchStoreRequest\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.pcmi.v1.BatchStoreItemR\x05items\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"\xc0\x01\n" +
	"\x14BatchStoreItemResult\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12(\n" +
	"\rsuperseded_id\x18\x05 \x01(\x03H\x00R\fsupersededId\x88\x01\x01\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05errorB\x10\n" +
	"\x0e_superseded_id\"c\n" +
	"\x12BatchStoreResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.pcmi.v1.BatchStoreItemResultR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x9f\x02\n" +
	"\x0fRetrieveRequest\x12\x1f\n" +
	"\vpath_prefix\x18\x01 \x01(\tR\n" +
	"pathPrefix\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"tags_match\x18\x06 \x01(\tR\ttagsMatch\x12\"\n" +
	"\ras_of_rfc3339\x18\a \x01(\tR\vasOfRfc3339\x12&\n" +
	"\x0fsource_agent_id\x18\b \x01(\tR\rsourceAgentId\x12'\n" +
	"\x0fembedding_space\x18\t \x01(\tR\x0eembeddingSpace\"\xd9\x04\n" +
	"\rRetrieveEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12'\n" +
	"\x0frelevance_score\x18\x05 \x01(\x01R\x0erelevanceScore\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\x12#\n" +
	"\rmetadata_json\x18\a \x01(\tR\fmetadataJson\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12'\n" +
	"\x0fembedding_model\x18\t \x01(\tR\x0eembeddingModel\x12'\n" +
	"\x0fembedding_space\x18\n" +
	" \x01(\tR\x0eembeddingSpace\x12,\n" +
	"\x12valid_from_rfc3339\x18\v \x01(\tR\x10validFromRfc3339\x12(\n" +
	"\x10valid_to_rfc3339\x18\f \x01(\tR\x0evalidToRfc3339\x12&\n" +
	"\x0fsource_agent_id\x18\r \x01(\tR\rsourceAgentId\x12&\n" +
	"\x0fsource_event_id\x18\x0e \x01(\tR\rsourceEventId\x12,\n" +
	"\x12created_at_rfc3339\x18\x0f \x01(\tR\x10createdAtRfc3339\x12+\n" +
	"\x11content_encrypted\x18\x10 \x01(\bR\x10contentEncrypted\x12\x1c\n" +
	"\tembedding\x18\x11 \x03(\x02R\tembedding\"Z\n" +
	"\x10RetrieveResponse\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.pcmi.v1.RetrieveEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x89\x02\n" +
	"\x12BatchRetrieveQuery\x12\x1f\n" +
	"\vpath_prefix\x18\x01 \x01(\tR\n" +
	"pathPrefix\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"tags_match\x18\x05 \x01(\tR\ttagsMatch\x12\"\n" +
	"\ras_of_rfc3339\x18\x06 \x01(\tR\vasOfRfc3339\x12&\n" +
	"\x0fsource_agent_id\x18\a \x01(\tR\rsourceAgentId\x12'\n" +
	"\x0fembedding_space\x18\b \x01(\tR\x0eembeddingSpace\"f\n" +
	"\x14BatchRetrieveRequest\x125\n" +
	"\aqueries\x18\x01 \x03(\v2\x1b.pcmi.v1.BatchRetrieveQueryR\aqueries\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"]\n" +
	"\x13BatchRetrieveResult\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.pcmi.v1.RetrieveEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"e\n" +
	"\x15BatchRetrieveResponse\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.pcmi.v1.BatchRetrieveResultR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\",\n" +
	"\x14RetrieveStreamHeader\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\"\x83\x01\n" +
	"\x11RetrieveStreamMsg\x127\n" +
	"\x06header\x18\x01 \x01(\v2\x1d.pcmi.v1.RetrieveStreamHeaderH\x00R\x06header\x12.\n" +
	"\x05entry\x18\x02 \x01(\v2\x16.pcmi.v1.RetrieveEntryH\x00R\x05entryB\x05\n" +
	"\x03msg\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"}\n" +
	"\x10GetMemoryRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\"\n" +
	"\ras_of_rfc3339\x18\x04 \x01(\tR\vasOfRfc3339\"A\n" +
	"\x11GetMemoryResponse\x12,\n" +
	"\x05entry\x18\x01 \x01(\v2\x16.pcmi.v1.RetrieveEntryR\x05entry\"f\n" +
	"\x0eCompactRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12'\n" +
	"\x0fkeep_superseded\x18\x03 \x01(\x05R\x0ekeepSuperseded\"s\n" +
	"\x0fCompactResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\rdeleted_count\x18\x02 \x01(\x05R\fdeletedCount\x12'\n" +
	"\x0fkeep_superseded\x18\x03 \x01(\x05R\x0ekeepSuperseded2\xde\x04\n" +
	"\rMemoryService\x126\n" +
	"\x05Store\x12\x15.pcmi.v1.StoreRequest\x1a\x16.pcmi.v1.StoreResponse\x12E\n" +
	"\n" +
	"BatchStore\x12\x1a.pcmi.v1.BatchStoreRequest\x1a\x1b.pcmi.v1.BatchStoreResponse\x12?\n" +
	"\bRetrieve\x12\x18.pcmi.v1.RetrieveRequest\x1a\x19.pcmi.v1.RetrieveResponse\x12N\n" +
	"\rBatchRetrieve\x12\x1d.pcmi.v1.BatchRetrieveRequest\x1a\x1e.pcmi.v1.BatchRetrieveResponse\x12H\n" +
	"\x0eRetrieveStream\x12\x18.pcmi.v1.RetrieveRequest\x1a\x1a.pcmi.v1.RetrieveStreamMsg0\x01\x129\n" +
	"\x06Health\x12\x16.pcmi.v1.HealthRequest\x1a\x17.pcmi.v1.HealthResponse\x126\n" +
	"\x05Ready\x12\x15.pcmi.v1.ReadyRequest\x1a\x16.pcmi.v1.ReadyResponse\x12B\n" +
	"\tGetMemory\x12\x19.pcmi.v1.GetMemoryRequest\x1a\x1a.pcmi.v1.GetMemoryResponse\x12<\n" +
	"\aCompact\x12\x17.pcmi.v1.CompactRequest\x1a\x18.pcmi.v1.CompactResponseB9Z7github.com/marco-spagn/pcmi/internal/grpc/pcmiv1;pcmiv1b\x06proto3"

var (
	file_pcmi_v1_memory_proto_rawDescOnce sync.Once
	file_pcmi_v1_memory_proto_rawDescData []byte
)

func file_pcmi_v1_memory_proto_rawDescGZIP() []byte {
	file_pcmi_v1_memory_proto_rawDescOnce.Do(func() {
		file_pcmi_v1_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pcmi_v1_memory_proto_rawDesc), len(file_pcmi_v1_memory_proto_rawDesc)))
	})
	return file_pcmi_v1_memory_proto_rawDescData
}

var file_pcmi_v1_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_pcmi_v1_memory_proto_goTypes = []any{
	(*ReadyRequest)(nil),          // 0: pcmi.v1.ReadyRequest
	(*ReadyResponse)(nil),         // 1: pcmi.v1.ReadyResponse
	(*StoreRequest)(nil),          // 2: pcmi.v1.StoreRequest
	(*StoreResponse)(nil),         // 3: pcmi.v1.StoreResponse
	(*BatchStoreItem)(nil),        // 4: pcmi.v1.BatchStoreItem
	(*BatchStoreRequest)(nil),     // 5: pcmi.v1.BatchStoreRequest
	(*BatchStoreItemResult)(nil),  // 6: pcmi.v1.BatchStoreItemResult
	(*BatchStoreResponse)(nil),    // 7: pcmi.v1.BatchStoreResponse
	(*RetrieveRequest)(nil),       // 8: pcmi.v1.RetrieveRequest
	(*RetrieveEntry)(nil),         // 9: pcmi.v1.RetrieveEntry
	(*RetrieveResponse)(nil),      // 10: pcmi.v1.RetrieveResponse
	(*BatchRetrieveQuery)(nil),    // 11: pcmi.v1.BatchRetrieveQuery
	(*BatchRetrieveRequest)(nil),  // 12: pcmi.v1.BatchRetrieveRequest
	(*BatchRetrieveResult)(nil),   // 13: pcmi.v1.BatchRetrieveResult
	(*BatchRetrieveResponse)(nil), // 14: pcmi.v1.BatchRetrieveResponse
	(*RetrieveStreamHeader)(nil),  // 15: pcmi.v1.RetrieveStreamHeader
	(*RetrieveStreamMsg)(nil),     // 16: pcmi.v1.RetrieveStreamMsg
	(*HealthRequest)(nil),         // 17: pcmi.v1.HealthRequest
	(*HealthResponse)(nil),        // 18: pcmi.v1.HealthResponse
	(*GetMemoryRequest)(nil),      // 19: pcmi.v1.GetMemoryRequest
	(*GetMemoryResponse)(nil),     // 20: pcmi.v1.GetMemoryResponse
	(*CompactRequest)(nil),        // 21: pcmi.v1.CompactRequest
	(*CompactResponse)(nil),       // 22: pcmi.v1.CompactResponse
}
var file_pcmi_v1_memory_proto_depIdxs = []int32{
	4,  // 0: pcmi.v1.BatchStoreRequest.items:type_name -> pcmi.v1.BatchStoreItem
	6,  // 1: pcmi.v1.BatchStoreResponse.results:type_name -> pcmi.v1.BatchStoreItemResult
	9,  // 2: pcmi.v1.RetrieveResponse.entries:type_name -> pcmi.v1.RetrieveEntry
	11, // 3: pcmi.v1.BatchRetrieveRequest.queries:type_name -> pcmi.v1.BatchRetrieveQuery
	9,  // 4: pcmi.v1.BatchRetrieveResult.entries:type_name -> pcmi.v1.RetrieveEntry
	13, // 5: pcmi.v1.BatchRetrieveResponse.results:type_name -> pcmi.v1.BatchRetrieveResult
	15, // 6: pcmi.v1.RetrieveStreamMsg.header:type_name -> pcmi.v1.RetrieveStreamHeader
	9,  // 7: pcmi.v1.RetrieveStreamMsg.entry:type_name -> pcmi.v1.RetrieveEntry
	9,  // 8: pcmi.v1.GetMemoryResponse.entry:type_name -> pcmi.v1.RetrieveEntry
	2,  // 9: pcmi.v1.MemoryService.Store:input_type -> pcmi.v1.StoreRequest
	5,  // 10: pcmi.v1.MemoryService.BatchStore:input_type -> pcmi.v1.BatchStoreRequest
	8,  // 11: pcmi.v1.MemoryService.Retrieve:input_type -> pcmi.v1.RetrieveRequest
	12, // 12: pcmi.v1.MemoryService.BatchRetrieve:input_type -> pcmi.v1.BatchRetrieveRequest
	8,  // 13: pcmi.v1.MemoryService.RetrieveStream:input_type -> pcmi.v1.RetrieveRequest
	17, // 14: pcmi.v1.MemoryService.Health:input_type -> pcmi.v1.HealthRequest
	0,  // 15: pcmi.v1.MemoryService.Ready:input_type -> pcmi.v1.ReadyRequest
	19, // 16: pcmi.v1.MemoryService.GetMemory:input_type -> pcmi.v1.GetMemoryRequest
	21, // 17: pcmi.v1.MemoryService.Compact:input_type -> pcmi.v1.CompactRequest
	3,  // 18: pcmi.v1.MemoryService.Store:output_type -> pcmi.v1.StoreResponse
	7,  // 19: pcmi.v1.MemoryService.BatchStore:output_type -> pcmi.v1.BatchStoreResponse
	10, // 20: pcmi.v1.MemoryService.Retrieve:output_type -> pcmi.v1.RetrieveResponse
	14, // 21: pcmi.v1.MemoryService.BatchRetrieve:output_type -> pcmi.v1.BatchRetrieveResponse
	16, // 22: pcmi.v1.MemoryService.RetrieveStream:output_type -> pcmi.v1.RetrieveStreamMsg
	18, // 23: pcmi.v1.MemoryService.Health:output_type -> pcmi.v1.HealthResponse
	1,  // 24: pcmi.v1.MemoryService.Ready:output_type -> pcmi.v1.ReadyResponse
	20, // 25: pcmi.v1.MemoryService.GetMemory:output_type -> pcmi.v1.GetMemoryResponse
	22, // 26: pcmi.v1.MemoryService.Compact:output_type -> pcmi.v1.CompactResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pcmi_v1_memory_proto_init() }
func file_pcmi_v1_memory_proto_init() {
	if File_pcmi_v1_memory_proto != nil {
		return
	}
	file_pcmi_v1_memory_proto_msgTypes[3].OneofWrappers = []any{}
	file_pcmi_v1_memory_proto_msgTypes[6].OneofWrappers = []any{}
	file_pcmi_v1_memory_proto_msgTypes[16].OneofWrappers = []any{
		(*RetrieveStreamMsg_Header)(nil),
		(*RetrieveStreamMsg_Entry)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pcmi_v1_memory_proto_rawDesc), len(file_pcmi_v1_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pcmi_v1_memory_proto_goTypes,
		DependencyIndexes: file_pcmi_v1_memory_proto_depIdxs,
		MessageInfos:      file_pcmi_v1_memory_proto_msgTypes,
	}.Build()
	File_pcmi_v1_memory_proto = out.File
	file_pcmi_v1_memory_proto_goTypes = nil
	file_pcmi_v1_memory_proto_depIdxs = nil
}
