// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pcmi/v1/memory.proto

package pcmiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{0}
}

type ReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ready" or "not_ready"
	DatabaseOk    bool                   `protobuf:"varint,2,opt,name=database_ok,json=databaseOk,proto3" json:"database_ok,omitempty"`
	RedisOk       bool                   `protobuf:"varint,3,opt,name=redis_ok,json=redisOk,proto3" json:"redis_ok,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{1}
}

func (x *ReadyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReadyResponse) GetDatabaseOk() bool {
	if x != nil {
		return x.DatabaseOk
	}
	return false
}

func (x *ReadyResponse) GetRedisOk() bool {
	if x != nil {
		return x.RedisOk
	}
	return false
}

func (x *ReadyResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	ApiKey        string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{2}
}

func (x *StoreRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StoreRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StoreRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *StoreRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{3}
}

func (x *StoreResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StoreResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StoreResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type RetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PathPrefix    string                 `protobuf:"bytes,1,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	ApiKey        string                 `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{4}
}

func (x *RetrieveRequest) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *RetrieveRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RetrieveRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RetrieveRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type RetrieveEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Path           string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Version        int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	RelevanceScore float64                `protobuf:"fixed64,5,opt,name=relevance_score,json=relevanceScore,proto3" json:"relevance_score,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RetrieveEntry) Reset() {
	*x = RetrieveEntry{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveEntry) ProtoMessage() {}

func (x *RetrieveEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveEntry.ProtoReflect.Descriptor instead.
func (*RetrieveEntry) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{5}
}

func (x *RetrieveEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RetrieveEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RetrieveEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RetrieveEntry) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RetrieveEntry) GetRelevanceScore() float64 {
	if x != nil {
		return x.RelevanceScore
	}
	return 0
}

type RetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*RetrieveEntry       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{6}
}

func (x *RetrieveResponse) GetEntries() []*RetrieveEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *RetrieveResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{7}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pcmi_v1_memory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_memory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_memory_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_pcmi_v1_memory_proto protoreflect.FileDescriptor

const file_pcmi_v1_memory_proto_rawDesc = "" +
	"\n" +
	"\x14pcmi/v1/memory.proto\x12\apcmi.v1\"\x0e\n" +
	"\fReadyRequest\"}\n" +
	"\rReadyResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vdatabase_ok\x18\x02 \x01(\bR\n" +
	"databaseOk\x12\x19\n" +
	"\bredis_ok\x18\x03 \x01(\bR\aredisOk\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"z\n" +
	"\fStoreRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\tR\fmetadataJson\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\"Q\n" +
	"\rStoreResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\"w\n" +
	"\x0fRetrieveRequest\x12\x1f\n" +
	"\vpath_prefix\x18\x01 \x01(\tR\n" +
	"pathPrefix\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKey\"\x90\x01\n" +
	"\rRetrieveEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12'\n" +
	"\x0frelevance_score\x18\x05 \x01(\x01R\x0erelevanceScore\"Z\n" +
	"\x10RetrieveResponse\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.pcmi.v1.RetrieveEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\xfb\x01\n" +
	"\rMemoryService\x126\n" +
	"\x05Store\x12\x15.pcmi.v1.StoreRequest\x1a\x16.pcmi.v1.StoreResponse\x12?\n" +
	"\bRetrieve\x12\x18.pcmi.v1.RetrieveRequest\x1a\x19.pcmi.v1.RetrieveResponse\x129\n" +
	"\x06Health\x12\x16.pcmi.v1.HealthRequest\x1a\x17.pcmi.v1.HealthResponse\x126\n" +
	"\x05Ready\x12\x15.pcmi.v1.ReadyRequest\x1a\x16.pcmi.v1.ReadyResponseB9Z7github.com/marco-spagn/pcmi/internal/grpc/pcmiv1;pcmiv1b\x06proto3"

var (
	file_pcmi_v1_memory_proto_rawDescOnce sync.Once
	file_pcmi_v1_memory_proto_rawDescData []byte
)

func file_pcmi_v1_memory_proto_rawDescGZIP() []byte {
	file_pcmi_v1_memory_proto_rawDescOnce.Do(func() {
		file_pcmi_v1_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pcmi_v1_memory_proto_rawDesc), len(file_pcmi_v1_memory_proto_rawDesc)))
	})
	return file_pcmi_v1_memory_proto_rawDescData
}

var file_pcmi_v1_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pcmi_v1_memory_proto_goTypes = []any{
	(*ReadyRequest)(nil),     // 0: pcmi.v1.ReadyRequest
	(*ReadyResponse)(nil),    // 1: pcmi.v1.ReadyResponse
	(*StoreRequest)(nil),     // 2: pcmi.v1.StoreRequest
	(*StoreResponse)(nil),    // 3: pcmi.v1.StoreResponse
	(*RetrieveRequest)(nil),  // 4: pcmi.v1.RetrieveRequest
	(*RetrieveEntry)(nil),    // 5: pcmi.v1.RetrieveEntry
	(*RetrieveResponse)(nil), // 6: pcmi.v1.RetrieveResponse
	(*HealthRequest)(nil),    // 7: pcmi.v1.HealthRequest
	(*HealthResponse)(nil),   // 8: pcmi.v1.HealthResponse
}
var file_pcmi_v1_memory_proto_depIdxs = []int32{
	5, // 0: pcmi.v1.RetrieveResponse.entries:type_name -> pcmi.v1.RetrieveEntry
	2, // 1: pcmi.v1.MemoryService.Store:input_type -> pcmi.v1.StoreRequest
	4, // 2: pcmi.v1.MemoryService.Retrieve:input_type -> pcmi.v1.RetrieveRequest
	7, // 3: pcmi.v1.MemoryService.Health:input_type -> pcmi.v1.HealthRequest
	0, // 4: pcmi.v1.MemoryService.Ready:input_type -> pcmi.v1.ReadyRequest
	3, // 5: pcmi.v1.MemoryService.Store:output_type -> pcmi.v1.StoreResponse
	6, // 6: pcmi.v1.MemoryService.Retrieve:output_type -> pcmi.v1.RetrieveResponse
	8, // 7: pcmi.v1.MemoryService.Health:output_type -> pcmi.v1.HealthResponse
	1, // 8: pcmi.v1.MemoryService.Ready:output_type -> pcmi.v1.ReadyResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pcmi_v1_memory_proto_init() }
func file_pcmi_v1_memory_proto_init() {
	if File_pcmi_v1_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pcmi_v1_memory_proto_rawDesc), len(file_pcmi_v1_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pcmi_v1_memory_proto_goTypes,
		DependencyIndexes: file_pcmi_v1_memory_proto_depIdxs,
		MessageInfos:      file_pcmi_v1_memory_proto_msgTypes,
	}.Build()
	File_pcmi_v1_memory_proto = out.File
	file_pcmi_v1_memory_proto_goTypes = nil
	file_pcmi_v1_memory_proto_depIdxs = nil
}
