// PCMI Metrics gRPC API (PR #5 — Admin + /metrics gRPC parity).
//
// Mirrors the Prometheus scrape endpoint that today is HTTP-only at
// GET /metrics. The gRPC service does NOT replace Prometheus — it gives
// programmatic, fine-grained access for SDK clients that already speak
// gRPC and would otherwise have to spin up a separate HTTP client just
// to poll metrics.
//
//   GET    /metrics                      → MetricsService.Scrape
//   <new>                                → MetricsService.StreamScrape (server-stream)
//   <new>                                → MetricsService.GetMetric (single counter/gauge by name)
//
// Auth: same X-API-Key / role-based middleware as the rest of gRPC.
// Scrape is rate-limited per the RATE_LIMIT_RPM_READONLY bucket since
// it's a high-volume read operation typical of dashboards.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: pcmi/v1/metrics.proto

package pcmiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricsService_Scrape_FullMethodName       = "/pcmi.v1.MetricsService/Scrape"
	MetricsService_StreamScrape_FullMethodName = "/pcmi.v1.MetricsService/StreamScrape"
	MetricsService_GetMetric_FullMethodName    = "/pcmi.v1.MetricsService/GetMetric"
)

// MetricsServiceClient is the client API for MetricsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsServiceClient interface {
	// Scrape returns the full Prometheus text-format snapshot in one shot.
	// Equivalent to `curl /metrics`. The body field carries the raw text.
	Scrape(ctx context.Context, in *ScrapeRequest, opts ...grpc.CallOption) (*ScrapeResponse, error)
	// StreamScrape pushes the same text-format payload as a stream of
	// chunks — useful for very large metric registries (10k+ series) where
	// a single response would exceed the 4 MiB gRPC default message size.
	StreamScrape(ctx context.Context, in *ScrapeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScrapeChunk], error)
	// GetMetric returns the current value(s) of a named metric. For a
	// gauge this is a single number; for a histogram, multiple
	// (count, sum, buckets). Useful for ad-hoc UI dashboards that don't
	// want to parse the full text format.
	GetMetric(ctx context.Context, in *GetMetricRequest, opts ...grpc.CallOption) (*GetMetricResponse, error)
}

type metricsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsServiceClient(cc grpc.ClientConnInterface) MetricsServiceClient {
	return &metricsServiceClient{cc}
}

func (c *metricsServiceClient) Scrape(ctx context.Context, in *ScrapeRequest, opts ...grpc.CallOption) (*ScrapeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScrapeResponse)
	err := c.cc.Invoke(ctx, MetricsService_Scrape_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) StreamScrape(ctx context.Context, in *ScrapeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScrapeChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetricsService_ServiceDesc.Streams[0], MetricsService_StreamScrape_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScrapeRequest, ScrapeChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsService_StreamScrapeClient = grpc.ServerStreamingClient[ScrapeChunk]

func (c *metricsServiceClient) GetMetric(ctx context.Context, in *GetMetricRequest, opts ...grpc.CallOption) (*GetMetricResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricResponse)
	err := c.cc.Invoke(ctx, MetricsService_GetMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServiceServer is the server API for MetricsService service.
// All implementations must embed UnimplementedMetricsServiceServer
// for forward compatibility.
type MetricsServiceServer interface {
	// Scrape returns the full Prometheus text-format snapshot in one shot.
	// Equivalent to `curl /metrics`. The body field carries the raw text.
	Scrape(context.Context, *ScrapeRequest) (*ScrapeResponse, error)
	// StreamScrape pushes the same text-format payload as a stream of
	// chunks — useful for very large metric registries (10k+ series) where
	// a single response would exceed the 4 MiB gRPC default message size.
	StreamScrape(*ScrapeRequest, grpc.ServerStreamingServer[ScrapeChunk]) error
	// GetMetric returns the current value(s) of a named metric. For a
	// gauge this is a single number; for a histogram, multiple
	// (count, sum, buckets). Useful for ad-hoc UI dashboards that don't
	// want to parse the full text format.
	GetMetric(context.Context, *GetMetricRequest) (*GetMetricResponse, error)
	mustEmbedUnimplementedMetricsServiceServer()
}

// UnimplementedMetricsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsServiceServer struct{}

func (UnimplementedMetricsServiceServer) Scrape(context.Context, *ScrapeRequest) (*ScrapeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Scrape not implemented")
}
func (UnimplementedMetricsServiceServer) StreamScrape(*ScrapeRequest, grpc.ServerStreamingServer[ScrapeChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamScrape not implemented")
}
func (UnimplementedMetricsServiceServer) GetMetric(context.Context, *GetMetricRequest) (*GetMetricResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetric not implemented")
}
func (UnimplementedMetricsServiceServer) mustEmbedUnimplementedMetricsServiceServer() {}
func (UnimplementedMetricsServiceServer) testEmbeddedByValue()                        {}

// UnsafeMetricsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServiceServer will
// result in compilation errors.
type UnsafeMetricsServiceServer interface {
	mustEmbedUnimplementedMetricsServiceServer()
}

func RegisterMetricsServiceServer(s grpc.ServiceRegistrar, srv MetricsServiceServer) {
	// If the following call panics, it indicates UnimplementedMetricsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricsService_ServiceDesc, srv)
}

func _MetricsService_Scrape_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScrapeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).Scrape(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_Scrape_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).Scrape(ctx, req.(*ScrapeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_StreamScrape_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScrapeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetricsServiceServer).StreamScrape(m, &grpc.GenericServerStream[ScrapeRequest, ScrapeChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsService_StreamScrapeServer = grpc.ServerStreamingServer[ScrapeChunk]

func _MetricsService_GetMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).GetMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_GetMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).GetMetric(ctx, req.(*GetMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricsService_ServiceDesc is the grpc.ServiceDesc for MetricsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pcmi.v1.MetricsService",
	HandlerType: (*MetricsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Scrape",
			Handler:    _MetricsService_Scrape_Handler,
		},
		{
			MethodName: "GetMetric",
			Handler:    _MetricsService_GetMetric_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamScrape",
			Handler:       _MetricsService_StreamScrape_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pcmi/v1/metrics.proto",
}
