// PCMI Metrics gRPC API (PR #5 — Admin + /metrics gRPC parity).
//
// Mirrors the Prometheus scrape endpoint that today is HTTP-only at
// GET /metrics. The gRPC service does NOT replace Prometheus — it gives
// programmatic, fine-grained access for SDK clients that already speak
// gRPC and would otherwise have to spin up a separate HTTP client just
// to poll metrics.
//
//   GET    /metrics                      → MetricsService.Scrape
//   <new>                                → MetricsService.StreamScrape (server-stream)
//   <new>                                → MetricsService.GetMetric (single counter/gauge by name)
//
// Auth: same X-API-Key / role-based middleware as the rest of gRPC.
// Scrape is rate-limited per the RATE_LIMIT_RPM_READONLY bucket since
// it's a high-volume read operation typical of dashboards.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pcmi/v1/metrics.proto

package pcmiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScrapeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OpenMetrics output format. Default = false (Prometheus text format).
	OpenMetrics   bool `protobuf:"varint,1,opt,name=open_metrics,json=openMetrics,proto3" json:"open_metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeRequest) Reset() {
	*x = ScrapeRequest{}
	mi := &file_pcmi_v1_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeRequest) ProtoMessage() {}

func (x *ScrapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeRequest.ProtoReflect.Descriptor instead.
func (*ScrapeRequest) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *ScrapeRequest) GetOpenMetrics() bool {
	if x != nil {
		return x.OpenMetrics
	}
	return false
}

type ScrapeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The complete metrics body, UTF-8 encoded text. May be empty if the
	// registry has not yet received any observations.
	Body          []byte `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	ContentType   string `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeResponse) Reset() {
	*x = ScrapeResponse{}
	mi := &file_pcmi_v1_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeResponse) ProtoMessage() {}

func (x *ScrapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeResponse.ProtoReflect.Descriptor instead.
func (*ScrapeResponse) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *ScrapeResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ScrapeResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type ScrapeChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Last          bool                   `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeChunk) Reset() {
	*x = ScrapeChunk{}
	mi := &file_pcmi_v1_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeChunk) ProtoMessage() {}

func (x *ScrapeChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeChunk.ProtoReflect.Descriptor instead.
func (*ScrapeChunk) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *ScrapeChunk) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ScrapeChunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

type GetMetricRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fully-qualified metric name, e.g. "pcmi_memory_stores_total".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional label filter — entries are AND-matched. Empty map = all
	// series for the metric.
	Labels        map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricRequest) Reset() {
	*x = GetMetricRequest{}
	mi := &file_pcmi_v1_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricRequest) ProtoMessage() {}

func (x *GetMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricRequest.ProtoReflect.Descriptor instead.
func (*GetMetricRequest) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *GetMetricRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMetricRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type MetricSample struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Label set for this sample.
	Labels map[string]string `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// value carries the sample value.  For counters/gauges this is the
	// current value; for histograms one MetricSample is emitted per
	// bucket plus an aggregate count/sum (encoded as separate samples
	// with label "__pcmi_kind__" ∈ {bucket,count,sum}).
	Value         float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSample) Reset() {
	*x = MetricSample{}
	mi := &file_pcmi_v1_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSample) ProtoMessage() {}

func (x *MetricSample) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSample.ProtoReflect.Descriptor instead.
func (*MetricSample) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *MetricSample) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MetricSample) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetMetricResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Help text from the metric definition (Prometheus HELP line).
	Help string `protobuf:"bytes,2,opt,name=help,proto3" json:"help,omitempty"`
	// Metric type: counter | gauge | histogram | summary.
	Type          string          `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Samples       []*MetricSample `protobuf:"bytes,4,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricResponse) Reset() {
	*x = GetMetricResponse{}
	mi := &file_pcmi_v1_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricResponse) ProtoMessage() {}

func (x *GetMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pcmi_v1_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricResponse.ProtoReflect.Descriptor instead.
func (*GetMetricResponse) Descriptor() ([]byte, []int) {
	return file_pcmi_v1_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *GetMetricResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMetricResponse) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *GetMetricResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetMetricResponse) GetSamples() []*MetricSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

var File_pcmi_v1_metrics_proto protoreflect.FileDescriptor

const file_pcmi_v1_metrics_proto_rawDesc = "" +
	"\n" +
	"\x15pcmi/v1/metrics.proto\x12\apcmi.v1\"2\n" +
	"\rScrapeRequest\x12!\n" +
	"\fopen_metrics\x18\x01 \x01(\bR\vopenMetrics\"G\n" +
	"\x0eScrapeResponse\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"5\n" +
	"\vScrapeChunk\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12\x12\n" +
	"\x04last\x18\x02 \x01(\bR\x04last\"\xa0\x01\n" +
	"\x10GetMetricRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12=\n" +
	"\x06labels\x18\x02 \x03(\v2%.pcmi.v1.GetMetricRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x01\n" +
	"\fMetricSample\x129\n" +
	"\x06labels\x18\x01 \x03(\v2!.pcmi.v1.MetricSample.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x01\n" +
	"\x11GetMetricResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04help\x18\x02 \x01(\tR\x04help\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12/\n" +
	"\asamples\x18\x04 \x03(\v2\x15.pcmi.v1.MetricSampleR\asamples2\xcf\x01\n" +
	"\x0eMetricsService\x129\n" +
	"\x06Scrape\x12\x16.pcmi.v1.ScrapeRequest\x1a\x17.pcmi.v1.ScrapeResponse\x12>\n" +
	"\fStreamScrape\x12\x16.pcmi.v1.ScrapeRequest\x1a\x14.pcmi.v1.ScrapeChunk0\x01\x12B\n" +
	"\tGetMetric\x12\x19.pcmi.v1.GetMetricRequest\x1a\x1a.pcmi.v1.GetMetricResponseB9Z7github.com/marco-spagn/pcmi/internal/grpc/pcmiv1;pcmiv1b\x06proto3"

var (
	file_pcmi_v1_metrics_proto_rawDescOnce sync.Once
	file_pcmi_v1_metrics_proto_rawDescData []byte
)

func file_pcmi_v1_metrics_proto_rawDescGZIP() []byte {
	file_pcmi_v1_metrics_proto_rawDescOnce.Do(func() {
		file_pcmi_v1_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pcmi_v1_metrics_proto_rawDesc), len(file_pcmi_v1_metrics_proto_rawDesc)))
	})
	return file_pcmi_v1_metrics_proto_rawDescData
}

var file_pcmi_v1_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pcmi_v1_metrics_proto_goTypes = []any{
	(*ScrapeRequest)(nil),     // 0: pcmi.v1.ScrapeRequest
	(*ScrapeResponse)(nil),    // 1: pcmi.v1.ScrapeResponse
	(*ScrapeChunk)(nil),       // 2: pcmi.v1.ScrapeChunk
	(*GetMetricRequest)(nil),  // 3: pcmi.v1.GetMetricRequest
	(*MetricSample)(nil),      // 4: pcmi.v1.MetricSample
	(*GetMetricResponse)(nil), // 5: pcmi.v1.GetMetricResponse
	nil,                       // 6: pcmi.v1.GetMetricRequest.LabelsEntry
	nil,                       // 7: pcmi.v1.MetricSample.LabelsEntry
}
var file_pcmi_v1_metrics_proto_depIdxs = []int32{
	6, // 0: pcmi.v1.GetMetricRequest.labels:type_name -> pcmi.v1.GetMetricRequest.LabelsEntry
	7, // 1: pcmi.v1.MetricSample.labels:type_name -> pcmi.v1.MetricSample.LabelsEntry
	4, // 2: pcmi.v1.GetMetricResponse.samples:type_name -> pcmi.v1.MetricSample
	0, // 3: pcmi.v1.MetricsService.Scrape:input_type -> pcmi.v1.ScrapeRequest
	0, // 4: pcmi.v1.MetricsService.StreamScrape:input_type -> pcmi.v1.ScrapeRequest
	3, // 5: pcmi.v1.MetricsService.GetMetric:input_type -> pcmi.v1.GetMetricRequest
	1, // 6: pcmi.v1.MetricsService.Scrape:output_type -> pcmi.v1.ScrapeResponse
	2, // 7: pcmi.v1.MetricsService.StreamScrape:output_type -> pcmi.v1.ScrapeChunk
	5, // 8: pcmi.v1.MetricsService.GetMetric:output_type -> pcmi.v1.GetMetricResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pcmi_v1_metrics_proto_init() }
func file_pcmi_v1_metrics_proto_init() {
	if File_pcmi_v1_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pcmi_v1_metrics_proto_rawDesc), len(file_pcmi_v1_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pcmi_v1_metrics_proto_goTypes,
		DependencyIndexes: file_pcmi_v1_metrics_proto_depIdxs,
		MessageInfos:      file_pcmi_v1_metrics_proto_msgTypes,
	}.Build()
	File_pcmi_v1_metrics_proto = out.File
	file_pcmi_v1_metrics_proto_goTypes = nil
	file_pcmi_v1_metrics_proto_depIdxs = nil
}
